wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    code_path: code/experiments/lp_distmult_fb.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch:
  desc: null
  value: 1024
beta:
  desc: null
  value: 1
biases:
  desc: null
  value: false
check_simple:
  desc: null
  value: false
corrupt_global:
  desc: null
  value: false
decoder:
  desc: null
  value: distmult
edo:
  desc: null
  value: 0.46
emb:
  desc: null
  value: 128
epochs:
  desc: null
  value: 150
eval_int:
  desc: null
  value: 10
eval_size:
  desc: null
  value: null
final:
  desc: null
  value: false
init_method:
  desc: null
  value: uniform
init_parms:
  desc: null
  value:
  - -0.85
  - 0.85
limit_negatives:
  desc: null
  value: false
loss:
  desc: null
  value: ce
lr:
  desc: null
  value: 0.14118
lred:
  desc: null
  value: sum
model:
  desc: null
  value: classic
momentum:
  desc: null
  value: 0.0
name:
  desc: null
  value: fb
negative_rate:
  desc: null
  value:
  - 557
  - 0
  - 367
nweight:
  desc: null
  value: null
opt:
  desc: null
  value: adagrad
patience:
  desc: null
  value: 9
rdo:
  desc: null
  value: 0.36
reciprocal:
  desc: null
  value: false
reg_eweight:
  desc: null
  value: 1.55e-10
reg_exp:
  desc: null
  value: 3
reg_rweight:
  desc: null
  value: 3.93e-15
repeats:
  desc: null
  value: 1
sched:
  desc: null
  value: false
tb_dir:
  desc: null
  value: null
test_batch:
  desc: null
  value: 10
var:
  desc: null
  value: true
